classDiagram
direction LR
%%TEMA CITAS MEDICAS

class Paciente {
  +int IdPaciente
  +string NombreCompleto
  +int Edad
  +string Telefono
  +string Correo
  +bool Activo
}

class Medico {
  +int IdMedico
  +string Nombre_Completo
  +string Especialidad
  +bool Activo
}

class Cita {
  +int IdCita
  +int IdPaciente_FK
  +int IdMedico_FK
  +date Fecha
  +string Hora
  +string Estado
}

class Usuario {
  +int IdUsuario
  +string Nombre_Usuario
  +string Rol
  +bool Activo
}

Paciente "1" --> "0..*" Cita : agenda
Medico "1" --> "0..*" Cita : atiende
Usuario "1" --> "0..*" Cita : gestiona
