create table public.diagnostico (
  id bigint generated by default as identity not null,
  nombre text null,
  edad text null,
  sintomas text null,
  diagnostico text null,
  created_at timestamp with time zone not null default now(),
  constraint Diagnostico_pkey primary key (id)
) TABLESPACE pg_default;

INSERT INTO public.diagnostico (nombre, edad, sintomas, diagnostico) VALUES 
('Juan Perez', '45', 'Dolor en el pecho, dificultad para respirar', 'Posible angina de pecho'),
('Maria Gomez', '30', 'Erupción cutánea, picazón intensa', 'Dermatitis alérgica'),
('Carlos Sanchez', '5', 'Fiebre alta, tos persistente', 'Infección respiratoria aguda'),
('Ericka Porras', '50', 'Palpitaciones, fatiga', 'Arritmia cardíaca'),
('Luis Rodriguez', '60', 'Dolor de cabeza intenso, visión borrosa', 'Posible migraña o hipertensión'),
('Ana Martinez', '40', 'Dolor abdominal, náuseas', 'Gastritis o úlcera péptica'),
('Pedro Lopez', '35', 'Dolor en las articulaciones, hinchazón', 'Artritis reumatoide'),
('Sofia Ramirez', '25', 'Visión borrosa, dolor ocular', 'Posible glaucoma'),
('Diego Fernandez', '28', 'Ansiedad, insomnio, cambios de humor', 'Trastorno de ansiedad generalizada'),
('Laura Torres', '55', 'Aumento de peso inexplicable, fatiga extrema', 'Posible hipotiroidismo');