create table public.pacientes (
  id bigint generated by default as identity not null,
  nombre_completo text null,
  especialidad text null,
  fecha_cita text null,
  hora_cita text null,
  acciones text null,
  created_at timestamp with time zone not null default now(),
  constraint pacientes_pkey primary key (id)
) TABLESPACE pg_default;


INSERT INTO public.pacientes (nombre_completo, especialidad, fecha_cita, hora_cita, Acciones) VALUES 
('Juan Perez', 'Cardiología', '2024-07-01', '10:00:00', NULL),
('Maria Gomez', 'Dermatología', '2024-07-02', '11:30:00', NULL),
('Carlos Sanchez', 'Pediatría', '2024-07-03', '14:00:00', NULL),
('Ericka Porras', 'Cardiología', '2024-07-03', '16:00:00', NULL),
('Luis Rodriguez', 'Neurología', '2024-07-04', '09:00:00', NULL),
('Ana Martinez', 'Gastroenterología', '2024-07-05', '13:00:00', NULL),
('Pedro Lopez', 'Ortopedia', '2024-07-06', '15:30:00', NULL),
('Sofia Ramirez', 'Oftalmología', '2024-07-07', '10:30:00', NULL),
('Diego Fernandez', 'Psiquiatría', '2024-07-08', '11:00:00', NULL),
('Laura Torres', 'Endocrinología', '2024-07-09', '14:30:00', NULL),
('Jorge Martinez', 'Cardiología', '2024-07-10', '09:30:00', NULL),
('Lucia Gonzalez', 'Dermatología', '2024-07-11', '12:00:00', NULL),
('Andres Ramirez', 'Pediatría', '2024-07-12', '15:00:00', NULL),
('Sofia Lopez', 'Cardiología', '2024-07-13', '16:30:00', NULL),
('Diego Sanchez', 'Neurología', '2024-07-14', '10:00:00', NULL),
('Valentina Torres', 'Gastroenterología', '2024-07-15', '13:30:00', NULL),
('Miguel Fernandez', 'Ortopedia', '2024-07-16', '15:00:00', NULL),
('Isabella Ramirez', 'Oftalmología', '2024-07-17', '11:30:00', NULL),
('Santiago Gonzalez', 'Psiquiatría', '2024-07-18', '14:00:00', NULL),
('Camila Martinez', 'Endocrinología', '2024-07-19', '09:00:00', NULL);